---
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ ansible_env.ZSH_CUSTOM | default('~/.oh-my-zsh/custom') }}/plugins/zsh-autosuggestions"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ work_users }}"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.ZSH_CUSTOM | default('~/.oh-my-zsh/custom') }}/plugins/zsh-syntax-highlighting"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ work_users }}"

- name: Source ~/.bash_profile in ohmyzsh
  blockinfile:
    path: "~/.zshrc"
    block: |
      [[ ! -f $HOME/.bash_profile ]] || source $HOME/.bash_profile
    insertafter: EOF
    marker_begin: "BEGIN BASH PROFILE"
    marker_end: "END BASH PROFILE"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ work_users }}"
