---
- name: Add vpn alias
  blockinfile:
    path: "~/.bash_profile"
    # --servercert {{ item['servercert'] }} \
    block: |
      alias vpn-{{ item['name'] }}="! tmux has-session -t vpn-{{ item['name'] }} 2>/dev/null && \
        tmux new-session -s vpn-{{ item['name'] }} -d \" \
          echo '{{ item['password'] }}' | sudo openconnect \
            --protocol=gp \
            {{ item['server'] }} \
            --user={{ item['username'] }} \
            --passwd-on-stdin \
            --csd-wrapper=/usr/libexec/openconnect/hipreport.sh \
        \""
      alias vpn-{{ item['name'] }}-stop="tmux kill-session -t vpn-{{ item['name'] }}"
    insertbefore: EOF
    marker_begin: "BEGIN vpn-{{ item['name'] }}"
    marker_end: "END vpn-{{ item['name'] }}"
  become: yes
  become_user: "{{ item['become_user'] }}"
  with_items: "{{ vpn_meta }}"
