---
- name: get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: include arch config
  include_vars:
    file: "vars/arch/{{ deb_architecture.stdout }}.yml"
  no_log: true
  ignore_errors: true

- name: apt configure
  block:
    - name: backup apt sources.list
      copy:
        src: "/etc/apt/sources.list"
        dest: "/etc/apt/sources.list.back"
        owner: root
        group: root
        mode: 0644
        force: no
        remote_src: yes

    - name: change apt sources.list to tuna
      copy:
        content: |
          # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse

          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse

          # 预发布软件源，不建议启用
          # deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-proposed main restricted universe multiverse
          # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-proposed main restricted universe multiverse
        dest: "/etc/apt/sources.list"
        owner: root
        group: root
        mode: 0644
        force: yes

    - name: install open-vm-tools
      apt:
        name:
          - open-vm-tools
        state: present
      become: yes
      become_user: "{{ item }}"
      with_items: "{{ work_users }}"
  become: yes
  become_user: root

- name: upgrade kernel to {{ ubuntu_kernel }}
  include_role:
    name: "oscaner.ubuntu-kernel"

- name: apt update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: install packages
  apt:
    name:
      - build-essential
      - mesa-common-dev
      - openssl
      - fzf
    state: present
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ work_users }}"
